services:

  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

